### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by geopayme** [Marcdnd/electrum-cesc#1]
Are there any electrum servers currently running for CESC?

Thanks

**Comment by Marcdnd** [comment]
Yes,

electrum1.cryptoescudo.org
electrum2.cryptoescudo.org
electrum3.cryptoescudo.org

Its only experimental, not offical.

Best regards.

Marcdnd

2015-09-13 16:53 GMT-03:00 Adonis Valamontes notifications@github.com:

> Are there any electrum servers currently running for CESC?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1.

## 

SDS
Marcio Denadai

**Comment by geopayme** [comment]
Thank you, is that port 50001?

**Comment by Marcdnd** [comment]
Hello I am updating servers to v1.0.
Have a experimental server on electrum1.cryptoescudo.com.br (tcp/50001)
Could you please test for me?

thx

**Comment by geopayme** [comment]
Ok will do in few min

**Comment by geopayme** [comment]
Part of the testing I did this morning indicates that sending transactions
with 0 (zero) fees they never get processed.

Can you confirm these values?

feePerKb = value(100000000L); // 0 Zerado para testes normal 100 000
minNonDust = value(1000); // 0.00001 CESC mininput
softDustLimit = value(100000000L); // 0 CESC
softDustPolicy = SoftDustPolicy.BASE_FEE_FOR_EACH_SOFT_DUST_TXO;

On Fri, Oct 23, 2015 at 4:19 PM, Marcdnd notifications@github.com wrote:

> Hello I am updating servers to v1.0.
> Have a experimental server on electrum1.cryptoescudo.com.br (tcp/50001)
> Could you please test for me?
> 
> thx
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150568641
> .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
I set now mininput=0

Speak portuguese?

**Comment by geopayme** [comment]
Sorry, no, only English and Greek

**Comment by Marcdnd** [comment]
Ok, no problem!

It was you who spoke with Apollo to add the CESC in UberPay wallet?

**Comment by geopayme** [comment]
Yes

**Comment by geopayme** [comment]
Im running the wallet with cesc coin

**Comment by geopayme** [comment]
The coins come to the wallet, but with no network fee you cant send coins
out.

[image: Inline image 1]

On Fri, Oct 23, 2015 at 4:41 PM, Adonis Valamontes tony@geopay.me wrote:

> Im running the wallet with cesc coin

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
Oh great! 
You are the official developer?
I have a version of Coinomi with CESC, we plan to launch so stabilized in the servers.
And a another wallet would be great!

**Comment by geopayme** [comment]
Yes

My name is Adonis... and I develop the UberPay wallet concept. As I said
the wallet receives coins at this moment fine as you can see in the
electrum server, but it cant send out until the fee parameters are set for
the coin.

If you want me to test the  send feature just let me know. I get the coins
from the faucet on Bleutrade, but if you can spare few coins (10 or 20)
 coins for testing you can send them here _CfWBa3DVsfUQmPjkmpZHkv7momhu2xQ98c
(Bleutrade CESC Wallet)_

Cheers

On Fri, Oct 23, 2015 at 4:45 PM, Marcdnd notifications@github.com wrote:

> Oh great!
> You are the official developer?
> I have a version of Coinomi with CESC, we plan to launch so stabilized in
> the servers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150577555
> .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
Hello,

I wanted to clarify, I and not with coinomi, we use part of their core
engine and made enhancements, I just want to make sure you understand. :D
With that said, I look forward to getting your coin operating and available
in the UberPay wallet.

When ever you are ready to test the send option in the wallet let me know!

Adonis

On Fri, Oct 23, 2015 at 4:45 PM, Marcdnd notifications@github.com wrote:

> Oh great!
> You are the official developer?
> I have a version of Coinomi with CESC, we plan to launch so stabilized in
> the servers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150577555
> .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
I send 10 CESC to address: CfWBa3DVsfUQmPjkmpZHkv7momhu2xQ98c
Sorry I did understand, is this address on Uberpay wallet? Or a bleutrade?

**Comment by geopayme** [comment]
Bleu, since at the moment the cesc coin can only receive coins without
network fee defined the coins are stuck in the wallet. To you have the coin
fully functioning on the coinomi wallet?

**Comment by geopayme** [comment]
I received the 10 coins, thank you, it helps with the testing, if you have
the coin fully functional in the Coinomi wallet just send the coin profile
 I can update UberPay and send you a debug version to help you test. If you
like!

Adonis

On Fri, Oct 23, 2015 at 6:41 PM, Adonis Valamontes tony@geopay.me wrote:

> Bleu, since at the moment the cesc coin can only receive coins without
> network fee defined the coins are stuck in the wallet. To you have the coin
> fully functioning on the coinomi wallet?
> On Oct 23, 2015 6:32 PM, "Marcdnd" notifications@github.com wrote:
> 
> > I send 10 CESC to address: CfWBa3DVsfUQmPjkmpZHkv7momhu2xQ98c
> > Sorry I did understand, is this address on Uberpay wallet? Or a bleutrade?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150609113
> > .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
Yes, but not yet updated to the new experimental server. The servers in the domain cryptoescudo.org are still off.
The electrum client is fully functional on new experimental server.

**Comment by geopayme** [comment]
let me know when...

electrum1.cryptoescudo.com.br50001tcp26bd05934155612015-10-23 15:52:201.0
open2015-10-23 15:45:10OK1.0000 0.0844 0.0028electrum1.cryptoescudo.org50001
tcp26bd05934155612015-10-23 15:52:201.0open2015-10-23 15:37:15OK1.0000
1.0000 0.0703128.199.255.22750001tcp0closed2015-10-10 09:01:24CLOSED0.0000
0.0000 0.0000electrum-cesc.bysh.me50001tcp0closed2015-10-03
18:39:47CLOSED0.0000
0.0000 0.0000pool.denesfer.srv.br50001tcp0closed2015-10-06 13:08:10CLOSED0.0000
0.0000 0.0000electrum3.cryptoescudo.org50001tcp0closed2015-10-05 10:28:11
CLOSED0.0000 0.0000 0.0000electrum2.cryptoescudo.org50001tcp0closed2015-10-05
10:24:00CLOSED0.0000 0.0000 0.0000

On Fri, Oct 23, 2015 at 6:51 PM, Marcdnd notifications@github.com wrote:

> Yes, but not yet updated to the new experimental server. The servers in
> the domain cryptoescudo.org are still off.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150614245
> .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
While running the servers are:
These are off (official servers):
electrum1.cryptoescudo.org
electrum2.cryptoescudo.org
electrum3.cryptoescudo.org

This is out (Experimental v 0.9):
pool.denesfer.srv.br

Experimental/dev v1.0rc1: ON
electrum1.cryptoescudo.com.br

Maybe in 1 or 2 weeks the official servers are ON.

**Comment by geopayme** [comment]
great

On Fri, Oct 23, 2015 at 7:13 PM, Marcdnd notifications@github.com wrote:

> While running the servers are:
> These are off (official servers):
> electrum1.cryptoescudo.org
> electrum2.cryptoescudo.org
> electrum3.cryptoescudo.org
> 
> This is out (Experimental v 0.9):
> pool.denesfer.srv.br
> 
> Experimental/dev v1.0rc1: ON
> electrum1.cryptoescudo.com.br
> 
> Maybe in 1 or 2 weeks the official servers are ON.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marcdnd/electrum-cesc/issues/1#issuecomment-150622098
> .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by Marcdnd** [comment]
Servers running! Closed!
